---
title: "Determining the Reliability of Likert Data from User Behavior"
author: "Rob Fontenot"
date: "5/15/2019"
output: html_document
---

## The Problem

As a major retailer with over 300,000 associates, the Learning organization within the company seeks to track the effectiveness of their training through Level 1 surveys that measure the associate's reaction to a course. These surveys are optional at the end of all prescribed learning events, generally run from between 3 to 5 questions that ask the associate to rate the course content, materials, trainers, etc. from a scale of 1 (least) to 5 (most). 

For years, leadership have tracked this data and found that the scores range on the high end of the spectrum, giving little insight into the associates' true reactions. It's been theorized that associates are "pencil whipping" the surveys, i.e., choosing all 4s or 5s on the survey just to clear it and move onto their next course or task, without really considering what's being asked. 

This analysis will look at the answers provided by associates from a given merchandising department and look for trends in a given associate's history at answering the questions in the Level 1 surveys. For instance, if a given associate has taken 10 courses over their tenure and, on all or most of the questions, have answered with a value of "5," this may be indicative of "pencil whipping." 

If these trends can be identified, then it might be possible to either drop such answers from the overall aggregated scores for a given course or to weigh said answers in a way impact the aggregated scores less, giving a truer measure of the course's effectiveness.

## The Data

The data for this analysis can be drawn directly from the Learning Management System (LMS) Oracle database backend. The LMS stores upwards of 2,000,000 course completions per year, so to keep the dataset manageable, the data for a given merchandizing department (for instance, the Paint or Electronic's department) will be used. This dataset will still contain data from all geographies of the company and will be trended for approximately one year to look for a pattern of activity among the associates in that department. 

While sensitive HR data will be occluded from the dataset per company policy, some associate-level metadata may be pulled as dimensions for analysis (for instance, associate tenure, associate job role, date of hire, course completion dates, etc.). 

# Approach

An effort will be made to define "pencil whipping" in terms of the data in order to model a pattern that can be applied to other departments. As the model is built and the data analyzed, this definition is likely to evolve. 

The collection and aggregation of the Level 1 data has already been operationalized and data is updated weekly for leadership dashboards. If the model functions as intended, the model could be integrated into the code that pulls the Level 1 data, adjusting the weight of the data that falls in the pattern as determined by leadership (either dropping it entirely or weighing it differently). 